# Created with komac v2.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: jthedering.EqualizerAPO
PackageVersion: 1.4.1
PackageLocale: en-US
Publisher: jthedering
PublisherSupportUrl: https://sourceforge.net/projects/equalizerapo/support
Author: jthedering
PackageName: Equalizer APO
License: GPLv2
ShortDescription: Equalizer APO is a parametric / graphic equalizer for Windows
Moniker: equalizerapo
ManifestType: defaultLocale
ManifestVersion: 1.9.0
