# Created using wingetcreate 1.9.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: jthedering.EqualizerAPO
PackageVersion: 1.4.1
InstallerType: nullsoft
Installers:
- Architecture: x64
  InstallerUrl: https://sourceforge.net/projects/equalizerapo/files/1.4.1/EqualizerAPO-x64-1.4.1.exe/download
  InstallerSha256: 8793693663B17089063788235583D08A18016D20422B76AC39A6DC08DBC8ECB7
ManifestType: installer
ManifestVersion: 1.9.0
